interactive_brokers:
  host: "127.0.0.1"
  port: 7496
  client_id: 1

contract:
  symbol: "MES"
  sec_type: "FUT"
  exchange: "CME"
  currency: "USD"
  lastTradeDateOrContractMonth: "20250321"
  localSymbol: "MESH5"
  multiplier: "5"

data:
  historical_days: 1
  bar_size: "1 min"

indicators:
  EMA_period: 20
  RSI_period: 14
  ATR_period: 14
  VWAP_period: 0

strategy:
  RSI_overbought: 70
  RSI_oversold: 30

trading:
  max_position: 1
  stop_loss_pct: 0.005
  take_profit_pct: 0.01

logging:
  level: "INFO"
  # file: "bot.log"
